version: "3"

services:
    authentication:
        build: ./microservices/authentication
        environment: 
            - NODE_ENV=${NODE_ENV}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
            - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_VALID_TIME=${JWT_VALID_TIME}
        volumes: 
            - ./microservices/authentication/logs:/app/logs
        networks:
            - microservices

    content-management:
        build: ./microservices/content-management
        environment: 
            - NODE_ENV=${NODE_ENV}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
            - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
        networks: 
            - microservices

    account-operations:
        build: ./microservices/account-operations
        environment:
            - DB_URL=${DB_JDBC_URL}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - AUTHENTICATION_URL=authentication:9000
        networks: 
            - microservices

    proxy:
        build: ./proxy
        volumes:
            - ./proxy/logs:/tmp
        ports: 
            - "9901:9901"
            - "8000:8000"
            - "8001:8001"
            - "8002:8002"
        networks:
            - microservices

networks:
    microservices:
