version: "3"

services:
  authentication:
    build: ./microservices/authentication
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_VALID_TIME=${JWT_VALID_TIME}
    volumes:
      - ./microservices/authentication/logs:/app/logs
    networks:
      - microservices

  content-management:
    build: ./microservices/content-management
    environment:
      - DB_URL=jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_DATABASE
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTHENTICATION_URL=authentication:9000
    networks:
      - microservices

  payment:
    build: ./microservices/payment
    environment:
      - DB_URL=postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_DATABASE
      - PAYPAL_MODE=${PAYPAL_MODE}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    networks:
      - microservices

  resource-management-control:
    build: ./microservices/resource-management-control
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${DB_HOST}
      - TYPEORM_USERNAME=${DB_USERNAME}
      - TYPEORM_PASSWORD=${DB_PASSWORD}
      - TYPEORM_DATABASE=${DB_DATABASE}
      - TYPEORM_PORT=${DB_PORT}
      - TYPEORM_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=src/entity/*.js
    networks:
      - microservices

  resource-management:
    build: ./microservices/resource-management
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - RESOURCE_MANAGEMENT_CONTROL_URL=resource-management-control:9000
    ports:
      - "8100:8000" # to be removed
    networks:
      - microservices

  proxy:
    build: ./proxy
    volumes:
      - ./proxy/logs:/tmp
    ports:
      - "9901:9901"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    networks:
      - microservices

networks:
  microservices:
    ipam:
      config:
        - subnet: 172.20.0.0/16
