version: "3"

services:
    authentication:
        build: ./microservices/authentication
        env_file: 
            - ./env/authentication.env
        volumes: 
            - ./microservices/authentication/logs:/app/logs
        networks:
            - microservices

    proxy:
        build: ./proxy
        volumes:
            - ./proxy/logs:/tmp
        ports: 
            - "9901:9901"
            - "8000:8000"
            - "8002:8002"
        networks:
            - microservices

networks:
    microservices:
