name: Continuos Integration

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop

jobs:
    authentication_test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./microservices/authentication
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 13.x
            - uses: actions/cache@v1
              with:
                path: ~/.cache/yarn
                key: ${{runner.OS}}-node-${{hashFiles('${{env.working-directory}}/yarn.lock')}}
            - run: yarn install --frozen-lockfile
              working-directory: ${{env.working-directory}}
            - run: yarn test
              working-directory: ${{env.working-directory}}
    
# Content management


    account-operations_test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./microservices/account-operations
        steps:
            - uses: actions/checkout@v2
            - run: ./genproto.sh
              working-directory: ${{env.working-directory}}/src/main
            - uses: actions/setup-java@v1
              with:
                java-version: 13
            - uses: actions/cache@v1
              with:
                path: ~/.m2
                key: ${{runner.OS}}-java-${{hashFiles('${{env.working-directory}}/pom.xml')}}
            - run: mvn -B package
              working-directory: ${{env.working-directory}}

    client_test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 13.x
            - uses: actions/cache@v1
              with:
                path: ~/.cache/yarn
                key: ${{runner.OS}}-node-${{hashFiles('${{env.working-directory}}/yarn.lock')}}
            - run: yarn install --frozen-lockfile
              working-directory: ${{env.working-directory}}
            - run: yarn test --watch-all=false --passWithNoTests
              working-directory: ${{env.working-directory}}