name: Continuos Integration

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop

jobs:
    authentication_test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./microservices/authentication
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
                with:
                    node-version: 13.x
            - run: yarn install
                working-directory: ${{env.working-directory}}
            - run: yarn test
                working-directory: ${{env.working-directory}}